language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  - windows


env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings

install:
  - python -m pip install cython==0.29.17

script:
  - python setup.py sdist bdist_wheel