language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  - windows


env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings

install:
  - python -m pip install cython==0.29.17
  - python -m pip install cibuildwheel==1.4.1


script:
  - python -m cibuildwheel --output-dir wheelhouse


after_success:
  # if the release was tagged, upload them to PyPI
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
